main: grabbag\Main
api: 1.10.0
load: POSTWORLD

name: GrabBag
description: Collection of miscellaneous commands and listener modules
version: 1.4.1
author: aliuly

permissions:
    gb.cmd.players:
        default: true
        description: "allow players command"
    gb.cmd.ops:
        default: true
        description: "list server ops"
    gb.cmd.sudo:
        default: op
        description: "Allow to run command as another user"
    gb.cmd.gma:
        default: op
        description: "Allow to switch gamemode to Adventure"
    gb.cmd.gms:
        default: op
        description: "Allow to switch gamemode to survival"
    gb.cmd.gmc:
        default: op
        description: "Allow to switch gamemode to creative"
    gb.cmd.slay:
        default: op
        description: "Allow slaying players"
    gb.cmd.heal:
        default: op
        description: "Allow healing"
    gb.cmd.whois:
        default: op
        description: "Show player details"
    gb.cmd.whois.showip:
        default: op
        description: "Show player IP address"
    gb.cmd.timings:
        default: op
        description: "Show timings data"
    gb.cmd.seearmor:
        default: op
        description: "Show player's armor"
    gb.cmd.seeinv:
        default: op
        description: "Show player's inventory"
    gb.cmd.clearinv:
        default: op
        description: "Clear player's inventory"
    gb.cmd.get:
        default: op
        description: "Get blocks"
    gb.spawnarmor.receive:
        default: true
        description: "allows to receive armor when you spawn"
    gb.spawnitems.receive:
        default: true
        description: "allows to receive items when you spawn"
    gb.compasstp.allow:
        default: op
        description: "Allow players to use Compass to Teleport"
    gb.cmd.shield:
        default: op
        description: "Allow players to become invulnerable"
    gb.cmd.servicemode:
        default: op
        description: "Allow access to service mode command"
    gb.servicemode.allow:
        default: op
        description: "Allow login when in service mode."
    gb.cmd.opms:
        default: true
        description: "Allow to send op only messages"
    gb.cmd.entities:
        default: op
        description: "Access entities command"
    gb.cmd.mute:
        default: op
        description: "mute/unmute"
    gb.cmd.freeze:
        default: op
        description: "freeze/thaw users"
    gb.cmd.after:
        default: op
        description: "Schedule commands"
    gb.cmd.rpt:
        default: true
        description: "Report issues"
    gb.cmd.rpt.read:
        default: op
        description: "Read reported issues"
    gb.ubab.override:
        default: false
        description: "Blocks that can not be broken"
    gb.cmd.summon:
        default: op
        description: "Summon|Dismiss command"
    gb.cmd.pushpoptp:
        default: op
        description: "push/pop teleport"
